export const data = [
  {
    image: 'https://loremflickr.com/640/480',
    name: 'name 1',
    sku: 'sku 1',
    category: 'category 1',
    brand: 'brand 1',
    model: 'model 1',
    stock: 67,
    lastTransaction: 'lastTransaction 1',
    transactionQty: 40,
    company: 'company 1',
    manager: 'manager 1',
    transactionDate: 'transactionDate 1',
    _id: '1',
  },
  {
    image: 'https://loremflickr.com/640/480',
    name: 'name 2',
    sku: 'sku 2',
    category: 'category 2',
    brand: 'brand 2',
    model: 'model 2',
    stock: 61,
    lastTransaction: 'lastTransaction 2',
    transactionQty: 47,
    company: 'company 2',
    manager: 'manager 2',
    transactionDate: 'transactionDate 2',
    _id: '2',
  },
  {
    image: 'https://loremflickr.com/640/480',
    name: 'name 3',
    sku: 'sku 3',
    category: 'category 3',
    brand: 'brand 3',
    model: 'model 3',
    stock: 61,
    lastTransaction: 'lastTransaction 3',
    transactionQty: 80,
    company: 'company 3',
    manager: 'manager 3',
    transactionDate: 'transactionDate 3',
    _id: '3',
  },
  {
    image: 'https://loremflickr.com/640/480',
    name: 'name 4',
    sku: 'sku 4',
    category: 'category 4',
    brand: 'brand 4',
    model: 'model 4',
    stock: 13,
    lastTransaction: 'lastTransaction 4',
    transactionQty: 52,
    company: 'company 4',
    manager: 'manager 4',
    transactionDate: 'transactionDate 4',
    _id: '4',
  },
  {
    image: 'https://loremflickr.com/640/480',
    name: 'name 5',
    sku: 'sku 5',
    category: 'category 5',
    brand: 'brand 5',
    model: 'model 5',
    stock: 83,
    lastTransaction: 'lastTransaction 5',
    transactionQty: 27,
    company: 'company 5',
    manager: 'manager 5',
    transactionDate: 'transactionDate 5',
    _id: '5',
  },
  {
    image: 'https://loremflickr.com/640/480',
    name: 'name 6',
    sku: 'sku 6',
    category: 'category 6',
    brand: 'brand 6',
    model: 'model 6',
    stock: 65,
    lastTransaction: 'lastTransaction 6',
    transactionQty: 56,
    company: 'company 6',
    manager: 'manager 6',
    transactionDate: 'transactionDate 6',
    _id: '6',
  },
  {
    image: 'https://loremflickr.com/640/480',
    name: 'name 7',
    sku: 'sku 7',
    category: 'category 7',
    brand: 'brand 7',
    model: 'model 7',
    stock: 70,
    lastTransaction: 'lastTransaction 7',
    transactionQty: 89,
    company: 'company 7',
    manager: 'manager 7',
    transactionDate: 'transactionDate 7',
    _id: '7',
  },
  {
    image: 'https://loremflickr.com/640/480',
    name: 'name 8',
    sku: 'sku 8',
    category: 'category 8',
    brand: 'brand 8',
    model: 'model 8',
    stock: 39,
    lastTransaction: 'lastTransaction 8',
    transactionQty: 31,
    company: 'company 8',
    manager: 'manager 8',
    transactionDate: 'transactionDate 8',
    _id: '8',
  },
  {
    image: 'https://loremflickr.com/640/480',
    name: 'name 9',
    sku: 'sku 9',
    category: 'category 9',
    brand: 'brand 9',
    model: 'model 9',
    stock: 92,
    lastTransaction: 'lastTransaction 9',
    transactionQty: 28,
    company: 'company 9',
    manager: 'manager 9',
    transactionDate: 'transactionDate 9',
    _id: '9',
  },
  {
    image: 'https://loremflickr.com/640/480',
    name: 'name 10',
    sku: 'sku 10',
    category: 'category 10',
    brand: 'brand 10',
    model: 'model 10',
    stock: 86,
    lastTransaction: 'lastTransaction 10',
    transactionQty: 26,
    company: 'company 10',
    manager: 'manager 10',
    transactionDate: 'transactionDate 10',
    _id: '10',
  },
  {
    image: 'https://loremflickr.com/640/480',
    name: 'name 11',
    sku: 'sku 11',
    category: 'category 11',
    brand: 'brand 11',
    model: 'model 11',
    stock: 80,
    lastTransaction: 'lastTransaction 11',
    transactionQty: 59,
    company: 'company 11',
    manager: 'manager 11',
    transactionDate: 'transactionDate 11',
    _id: '11',
  },
  {
    image: 'https://loremflickr.com/640/480',
    name: 'name 12',
    sku: 'sku 12',
    category: 'category 12',
    brand: 'brand 12',
    model: 'model 12',
    stock: 38,
    lastTransaction: 'lastTransaction 12',
    transactionQty: 28,
    company: 'company 12',
    manager: 'manager 12',
    transactionDate: 'transactionDate 12',
    _id: '12',
  },
  {
    image: 'https://loremflickr.com/640/480',
    name: 'name 13',
    sku: 'sku 13',
    category: 'category 13',
    brand: 'brand 13',
    model: 'model 13',
    stock: 85,
    lastTransaction: 'lastTransaction 13',
    transactionQty: 75,
    company: 'company 13',
    manager: 'manager 13',
    transactionDate: 'transactionDate 13',
    _id: '13',
  },
  {
    image: 'https://loremflickr.com/640/480',
    name: 'name 14',
    sku: 'sku 14',
    category: 'category 14',
    brand: 'brand 14',
    model: 'model 14',
    stock: 73,
    lastTransaction: 'lastTransaction 14',
    transactionQty: 80,
    company: 'company 14',
    manager: 'manager 14',
    transactionDate: 'transactionDate 14',
    _id: '14',
  },
  {
    image: 'https://loremflickr.com/640/480',
    name: 'name 15',
    sku: 'sku 15',
    category: 'category 15',
    brand: 'brand 15',
    model: 'model 15',
    stock: 91,
    lastTransaction: 'lastTransaction 15',
    transactionQty: 48,
    company: 'company 15',
    manager: 'manager 15',
    transactionDate: 'transactionDate 15',
    _id: '15',
  },
  {
    image: 'https://loremflickr.com/640/480',
    name: 'name 16',
    sku: 'sku 16',
    category: 'category 16',
    brand: 'brand 16',
    model: 'model 16',
    stock: 62,
    lastTransaction: 'lastTransaction 16',
    transactionQty: 36,
    company: 'company 16',
    manager: 'manager 16',
    transactionDate: 'transactionDate 16',
    _id: '16',
  },
  {
    image: 'https://loremflickr.com/640/480',
    name: 'name 17',
    sku: 'sku 17',
    category: 'category 17',
    brand: 'brand 17',
    model: 'model 17',
    stock: 93,
    lastTransaction: 'lastTransaction 17',
    transactionQty: 46,
    company: 'company 17',
    manager: 'manager 17',
    transactionDate: 'transactionDate 17',
    _id: '17',
  },
  {
    image: 'https://loremflickr.com/640/480',
    name: 'name 18',
    sku: 'sku 18',
    category: 'category 18',
    brand: 'brand 18',
    model: 'model 18',
    stock: 5,
    lastTransaction: 'lastTransaction 18',
    transactionQty: 13,
    company: 'company 18',
    manager: 'manager 18',
    transactionDate: 'transactionDate 18',
    _id: '18',
  },
  {
    image: 'https://loremflickr.com/640/480',
    name: 'name 19',
    sku: 'sku 19',
    category: 'category 19',
    brand: 'brand 19',
    model: 'model 19',
    stock: 4,
    lastTransaction: 'lastTransaction 19',
    transactionQty: 71,
    company: 'company 19',
    manager: 'manager 19',
    transactionDate: 'transactionDate 19',
    _id: '19',
  },
  {
    image: 'https://loremflickr.com/640/480',
    name: 'name 20',
    sku: 'sku 20',
    category: 'category 20',
    brand: 'brand 20',
    model: 'model 20',
    stock: 18,
    lastTransaction: 'lastTransaction 20',
    transactionQty: 51,
    company: 'company 20',
    manager: 'manager 20',
    transactionDate: 'transactionDate 20',
    _id: '20',
  },
  {
    image: 'https://loremflickr.com/640/480',
    name: 'name 21',
    sku: 'sku 21',
    category: 'category 21',
    brand: 'brand 21',
    model: 'model 21',
    stock: 66,
    lastTransaction: 'lastTransaction 21',
    transactionQty: 60,
    company: 'company 21',
    manager: 'manager 21',
    transactionDate: 'transactionDate 21',
    _id: '21',
  },
  {
    image: 'https://loremflickr.com/640/480',
    name: 'name 22',
    sku: 'sku 22',
    category: 'category 22',
    brand: 'brand 22',
    model: 'model 22',
    stock: 5,
    lastTransaction: 'lastTransaction 22',
    transactionQty: 14,
    company: 'company 22',
    manager: 'manager 22',
    transactionDate: 'transactionDate 22',
    _id: '22',
  },
  {
    image: 'https://loremflickr.com/640/480',
    name: 'name 23',
    sku: 'sku 23',
    category: 'category 23',
    brand: 'brand 23',
    model: 'model 23',
    stock: 89,
    lastTransaction: 'lastTransaction 23',
    transactionQty: 86,
    company: 'company 23',
    manager: 'manager 23',
    transactionDate: 'transactionDate 23',
    _id: '23',
  },
  {
    image: 'https://loremflickr.com/640/480',
    name: 'name 24',
    sku: 'sku 24',
    category: 'category 24',
    brand: 'brand 24',
    model: 'model 24',
    stock: 23,
    lastTransaction: 'lastTransaction 24',
    transactionQty: 52,
    company: 'company 24',
    manager: 'manager 24',
    transactionDate: 'transactionDate 24',
    _id: '24',
  },
  {
    image: 'https://loremflickr.com/640/480',
    name: 'name 25',
    sku: 'sku 25',
    category: 'category 25',
    brand: 'brand 25',
    model: 'model 25',
    stock: 30,
    lastTransaction: 'lastTransaction 25',
    transactionQty: 6,
    company: 'company 25',
    manager: 'manager 25',
    transactionDate: 'transactionDate 25',
    _id: '25',
  },
  {
    image: 'https://loremflickr.com/640/480',
    name: 'name 26',
    sku: 'sku 26',
    category: 'category 26',
    brand: 'brand 26',
    model: 'model 26',
    stock: 73,
    lastTransaction: 'lastTransaction 26',
    transactionQty: 62,
    company: 'company 26',
    manager: 'manager 26',
    transactionDate: 'transactionDate 26',
    _id: '26',
  },
  {
    image: 'https://loremflickr.com/640/480',
    name: 'name 27',
    sku: 'sku 27',
    category: 'category 27',
    brand: 'brand 27',
    model: 'model 27',
    stock: 66,
    lastTransaction: 'lastTransaction 27',
    transactionQty: 74,
    company: 'company 27',
    manager: 'manager 27',
    transactionDate: 'transactionDate 27',
    _id: '27',
  },
  {
    image: 'https://loremflickr.com/640/480',
    name: 'name 28',
    sku: 'sku 28',
    category: 'category 28',
    brand: 'brand 28',
    model: 'model 28',
    stock: 53,
    lastTransaction: 'lastTransaction 28',
    transactionQty: 69,
    company: 'company 28',
    manager: 'manager 28',
    transactionDate: 'transactionDate 28',
    _id: '28',
  },
  {
    image: 'https://loremflickr.com/640/480',
    name: 'name 29',
    sku: 'sku 29',
    category: 'category 29',
    brand: 'brand 29',
    model: 'model 29',
    stock: 96,
    lastTransaction: 'lastTransaction 29',
    transactionQty: 63,
    company: 'company 29',
    manager: 'manager 29',
    transactionDate: 'transactionDate 29',
    _id: '29',
  },
];
